### ISSUE TITLE
Does not appear to interrupt RequestAnimationFrame

### ISSUE THREAD

**Issue by jameswilddev** [samme/phaser-plugin-pause-render#8]
I have a use case where a (HTML) modal pops in front of the game, completely covering it.  During that time, the game should stop processing entirely to free up CPU for the HTML modal to remain responsive.

I've installed this plugin and it seems to work well; the game stops rendering and appears to stop processing physics/etc.  There is still measurable performance impact however and I can see RequestAnimationFrame calls in the browser's profiler.

![Screen Shot 2021-12-03 at 11 13 15](https://user-images.githubusercontent.com/3138458/144595815-66cdcfa1-5157-478a-b952-d6312e449125.png)

For now I'm manually drilling down into `game.loop.raf` and calling start/stop which seems to do the trick:

![Screen Shot 2021-12-03 at 11 42 22](https://user-images.githubusercontent.com/3138458/144596905-731afe8b-6909-47b6-aeb2-131da745ade8.png)

**Comment by samme** [comment]
That's expected, since the rendering pause isn't supposed to stop the game logic. Scenes and input are still updated.

For your case you have the right idea, which is to stop the RAF directly.
